title: tuilion
description: Cyber, code, and quiet thinking.

remote_theme: jekyll/minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

minima:
  skin: auto

  nav_pages:
    - about.md
    - posts.md
